[project]
name = "gen-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "google-genai>=1.46.0",
    "langchain-community>=0.3.30",
    "langchain-google-genai>=2.1.12",
    "langchain-google-vertexai>=3.0.1",
    "langchain-neo4j>=0.5.0",
    "langchain-qdrant>=0.2.1",
    "langchain-text-splitters>=0.3.11",
    "langfuse>=3.8.1",
    "langgraph>=1.0.1",
    "langgraph-checkpoint-mongodb>=0.2.1",
    "langsmith>=0.4.32",
    "mem0ai>=1.0.0",
    "openai>=1.99.7",
    "pip>=25.3",
    "pymongo>=4.15.3",
    "pypdf>=6.1.1",
    "rank-bm25>=0.2.2",
    "tiktoken>=0.11.0",
]
